### PR TITLE
fix: removed all console.log()'s from useNotes.js

### PR DESCRIPTION
**Pull request by t-li-projects**
Removed all `console.log()` lines & other elements made to support `console.log()`

eg. both `console.log()` and `if()` were removed
```js
if(…) { 
console.log(…) 
}
```

Additional semantic improvements to consistency (spacing & line breaks)

The reason I'm opening a **draft** request is that the code is **not tested** and that should probably be done.

<br>
<hr>
I'm new to open source projects so let me know if I messed anything up.
Have a good day!

### CODE REVIEW

**Review by PorthoGamesBR — CHANGES_REQUESTED** [review]
The ones inside catch functions can stay since they are actually alerting errors in the request and, for now, is the best way to see when this kind of error happens.

**Comment by PorthoGamesBR** [comment]
Im also new, so don't worry. Im still learning how to use GitHub _the right way._

**Comment by t-li-projects** [comment]
How's the new commit looking?
<br>
> Just a tip: even if is a simple bug fix, try creating a new branch for the fix.

Thanks for the tip!

**Comment by PorthoGamesBR** [comment]
> How's the new commit looking?
> 
> > Just a tip: even if is a simple bug fix, try creating a new branch for the fix.
> 
> Thanks for the tip!

Yes, because if i want, for example, to test your code before merging, i can accept your pull request and pull the branch to my local environment, execute and review it very fast. If you do not create a branch i will either need to create another remote to link to your personal repository and then create a branch from there or use the GitHub CLI to create a branch from the pull request instead.

Don't worry tho, i discovered this today too ksksksksksks I probably would have done the same if it was my first time contributing to a project. I will just test your code and send the review.

**Review by PorthoGamesBR — COMMENTED** [review]
Just change the catch in the addNote function and everything should be okay

**Comment by PorthoGamesBR** [comment]
@t-li-projects Sorry, my mistake, this code was wrong in the main branch also. I'm going to merge and fix it in a fix branch

**Review by PorthoGamesBR — APPROVED** [review]
Everything okay now, the console.log that were originally inside catch statements were re-added to them

**Comment by t-li-projects** [comment]
@PorthoGamesBR Thank you for the patience 🙏🙏

**Pull request merged**
